### ISSUE TITLE
RC issue and fix before release list

### ISSUE THREAD

**Issue by NonovUrbizniz** [CiFor/DayZ_Sahrani#106]
Important:
- [x] De-gun CH47 camo (Commented Out)
- [ ] Vilas gun configs?

Would Be Nice:
- [ ]  Refuel action item stacks when you get in and out of car
- [ ] remove propoganda posters from front of olezvina
- [ ] Fix Vilas Models as below
- [ ] billboards

DONE:
- [x]  Refuel Continues if you eject. (I think it's fine that way)
- [x] Change "Day" x to "Day 7 Attempt" x
- [x]  Clothes are all fucked. ATACS works, all others broke (Don't show pliskin's textures), Can't get on vehicle in ATACS 
- [x] Comment out bullet crafting
- [x] Update Version # in Main Menu to 0.7.7
- [x] CORRECT BOHEMIA SPELLING IN SPLASH SCREEN not "Behemia" Bohemia
- [x] A2 gas stations still there 
- [x] Do Credits
- [x] Do License
- [x] Do Changelog
- [x] fix Olezvina railing transperancy
- [x] Lobby does not work from what's on github now, I think you have un-sunk changes
- [x] no buildings on any islands yet. 
- [x] remove singleplayer?
- [x] test battleye
- [x] Move hints down or gear menu up so you can see hints while crafting in menu
- [x] Fix pecheng, PK, MK48

**Comment by NonovUrbizniz** [comment]
Re Models poking shirt through protective vest:

i know
[11:22:08 AM] vilas: on back
[11:22:21 AM] vilas: just remove polygons behind /under back of vest
[11:22:35 AM] vilas: cause i know, later i replaced this error
[11:22:39 AM] vilas: it happens on back of unit

Also add ability to carry backpack

**Comment by grafzahl** [comment]
Thing is... if you add lootable Buildings to Islands... its somehow a safe place to lootpile the shit out of every building even with 50 players on the server ^^

**Comment by xyberviri** [comment]
doesn't skalinsky on cherno have lootable buildings?

**Comment by NonovUrbizniz** [comment]
With the loot chances the way there are, it would be quicker to go back and forth between Pita and Tres Valles, or Cabo Santa Lucia and Siera Cresta, 

Also it takes having "made it" on the mainland to get to antigua or rahmadi so I think it's ok to reward the efforts with a bit of relaxation... 

Although once the zone map is in place islands might be a little harder to survive on than the mainland.

We didn't go nuts with buildings on the islands like some folks did ;-P

Rahmadi:
2 Hangers
1 ATC
1 Market
1 WIP
3-5 Industrial Sheds
1 Fueling station

Antigua 
1 WIP
1 ATC

Tank Island:
2 Barracks
1 WIP
1 Fueling Station
6 Camo Net Car Covers

**Comment by grafzahl** [comment]
Skalisty by default has no lootable Buildings ;)

I will see what i can produce today. And who do you mean with "We didn't go nuts with buildings on the islands like some folks did ;-P", i put a lot of buildings on rahmadi, but made them all spawn no loot :P
