### ISSUE TITLE
Seven's Super Happy cleanup list

### ISSUE THREAD

**Issue by NonovUrbizniz** [CiFor/DayZ_Sahrani#108]
Vilas Weapon Configs 
- ?? Fix please

Storage Crafting  - MOVE GEAR MENU (up) OR HINTS (down)
- [ ] Can't see items as you are placing them, they disappear when you hit close on the gear menu
- [x] Gunrack - Recipe says 3 and 3 only takes 3 wood + 2 nails? Leaves 1 nails in inventory - FIXED
- [ ] Box Storage - Change to your crate??
- [x] Box Storage - Says needs 3 and 6 only takes 3 wood + 2 nails leaves 4 nails in inventory  - FIXED

**Comment by NonovUrbizniz** [comment]
Billboards would also be cool, but again, either way I've got to push SOMETHING to dayz commander at 4 or 5 pm EST today. Can't keep floundering like this.

**Comment by Cookiezzz** [comment]
Box Storage - Says needs 3 and 6 only takes 3 wood + 2 nails leaves 4 nails in inventory - FIXED
Gunrack - Recipe says 3 and 3 only takes 3 wood + 2 nails? Leaves 1 nails in inventory - FIXED

Hope ya don't mind :)
