### ISSUE TITLE
Put loot on Airport Terminal Roof

### ISSUE THREAD

**Issue by NonovUrbizniz** [CiFor/DayZ_Sahrani#109]

**Comment by xyberviri** [comment]
is this the standard terminal like on the AF of cherno? there already is a loot pile at the top do you want another pile on top of the roof

**Comment by NonovUrbizniz** [comment]
Never saw your comment xberviri, it's the Arma1 Airport Terminal only on Paraiso AF:

http://resources.bisimulations.com/content/index.html?category=Objects&group=(game)_structures_-_buildings&object=land_letistni_hala

I put a buncha loot there last night
