### ISSUE TITLE
dum_istan2_01

### ISSUE THREAD

**Issue by M1lkm8n** [CiFor/DayZ_Sahrani#110]
anything in the geolod, firelod, and view lod needs to be convex and close with the exceptions of the proxies. the stairs are not closed and the balconies are not convex or closed. make simple shapes for the balconies currently they are just faces.

also bed_big_a is not part of ca. don't use it. try bed_husbands if it fits the style

**Comment by NonovUrbizniz** [comment]
Donald are you/have you worked on this? 

We're pulling the building from the current build, it's too "off" for primetime. 

I'm going to update the github with floorplans and pics. for all the buildings.
