### ISSUE TITLE
Sam and any other modellers kindly help bang out the official mod list

### ISSUE THREAD

**Issue by NonovUrbizniz** [CiFor/DayZ_Sahrani#111]
https://github.com/R4Z0R49/DayzMod-Private/issues/366

Any other modellers who want in let me know I will get you added to the official dev team.

**Comment by Cybersam248** [comment]
Hey man, I clicked the link and I got a page 404 error. But if it's
modelling, i'm in.

Ta

On 14 September 2013 05:55, NonovUrbizniz notifications@github.com wrote:

> R4Z0R49/DayzMod-Private#366https://github.com/R4Z0R49/DayzMod-Private/issues/366
> 
> Any other modellers who want in let me know I will get you added to the
> official dev team.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CiFor/DayZ_Sahrani/issues/111
> .

## 

_Joseph Samuel Taskis_
Character And Asset Modeller
| m: 07731122210
| e:taskis.s1@googlemail.com
| w: http://taskisjs.wordpress.com/

**Comment by NonovUrbizniz** [comment]
You've been added, and prodded on skype.... HAVE AT IT!!

**Comment by Cybersam248** [comment]
Awesome, will speak to you this afternoon thanks :)

On 19 September 2013 06:19, NonovUrbizniz notifications@github.com wrote:

> You've been added, and prodded on skype.... HAVE AT IT!!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CiFor/DayZ_Sahrani/issues/111#issuecomment-24717680
> .

## 

_Joseph Samuel Taskis_
Character And Asset Modeller
| m: 07731122210
| e:taskis.s1@googlemail.com
| w: http://taskisjs.wordpress.com/
