### ISSUE TITLE
Bug - Bandit Ghillie male or female does not create inventory normal ghille

### ISSUE THREAD

**Issue by NonovUrbizniz** [CiFor/DayZ_Sahrani#59]
￼14:55:48 "Cookiezzz": SniperBanditW_DZ
￼14:55:51 "Cookiezzz": SniperBandit_DZ
￼14:55:55 "Cookiezzz": Sniper1W_DZ

Are all missing lootable items Clothing packages

**Comment by EHDSeven** [comment]
Fixed
