### ISSUE TITLE
Add "Auto Refuel" to Mod

### ISSUE THREAD

**Issue by NonovUrbizniz** [CiFor/DayZ_Sahrani#70]
- [ ] Inventory Check for Jerry Can (eventually tubing kit as well)
- [ ] force player out of vehicle 
- [ ] Option Menu on
  - Above Ground Tanks 
  - Fuel Pump (Long term - IF Power Grid is Repaired and ON)
  - Eventually manhole cover area on ground of gas stations?
- [ ] select "auto refuel" plays total number of Action Anims Required w/o interuption
- [x] Provide Cancel Action option, or allow it to be broken if player moves

**Comment by EHDSeven** [comment]
Done for now.

**Comment by grafzahl** [comment]
Are you realy sure that we should provide auto-refuel by default on all kinds of gasstations? This makes the mod realy casual and unrealistic, like overwatch...

On our Server the best way was to only provide Auto-Refuel on the 2 Main-Airfields, so you create 2 Hotspots and have to decide if you go the easy & dangerous way of auto-refueling on a place where nearly everytime someone is around, or you search for a gas-tank somewhere on the map-border and refuel a little bit safer but it takes more time.

As it is now... its like you have unlimited fuel everywhere :-/

**Comment by EHDSeven** [comment]
Taken refuel at the white tanks, and changed it to choppers can only refuel at the military fuel pumps (must also land and turn of engine), you can now predict where people are going to fuel their choppers if they are retarded.
